In [395]:
import pandas as pd
import numpy as np
from numpy.random import default_rng

def normalize_dataset(df):
    return (df - df.min()) / (df.max() - df.min())

def sigmoid(s):
        return 1/(1 + np.exp(-s))
    
def randn(dim1, dim2, low, high):
    return (high - low) * rng.random((dim1, dim2)) + low

def sigmoid_prime(s):
        return sigmoid(s) * (1 - sigmoid(s))
    
def drop(arr, n):
    if (n > 0):
        return arr[n:]
    else:
        return arr[:n]

# Importar dados do banco de dados


In [396]:
data = pd.read_excel('./../dataset_okuyucu.xlsx')
data

Total Rotation Speed (rpm)  Welding Speed (mm/min)  \
0                          500                    6.25   
1                          500                   10.00   
2                          500                   16.00   
3                          500                   20.00   
4                          800                    6.25   
5                          800                   10.00   
6                          800                   16.00   
7                          800                   20.00   
8                         1000                    6.25   
9                         1000                   10.00   
10                        1000                   16.00   
11                        1000                   20.00   
12                        1250                    6.25   
13                        1250                   10.00   
14                        1250                   16.00   
15                        1250                   20.00   
16                        1500                    6.25   
17                        1500                   10.00   
18                        1500                   16.00   
19                        1500                   20.00   

    Tensile Strength (MPa)  Yield Strength (MPa)  Elongation (%)  \
0                      112                    86            3.04   
1                      104                    80            3.34   
2                      103                    78            3.71   
3                      102                    76            4.78   
4                      102                    77            5.22   
5                      101                    75            5.44   
6                       92                    66            5.52   
7                       91                    65            5.63   
8                       99                    75            5.65   
9                       91                    66            6.36   
10                      89                    63            6.94   
11                      88                    60            7.63   
12                      88                    60            7.00   
13                      87                    57            7.02   
14                      86                    56            7.36   
15                      84                    53            8.36   
16                      80                    58            7.45   
17                      79                    86           10.17   
18                      77                    52           10.39   
19                      76                    47           11.26   

    Hardness Weld (HV)  Hardness HAZ (HV)  
0                 27.2              27.60  
1                 27.5              28.00  
2                 28.0              28.30  
3                 28.2              28.50  
4                 26.8              26.55  
5                 27.0              26.60  
6                 27.6              27.00  
7                 27.8              27.60  
8                 26.4              26.00  
9                 26.8              24.80  
10                27.0              26.70  
11                27.2              27.20  
12                24.0              24.10  
13                24.8              24.80  
14                25.7              25.30  
15                26.1              25.90  
16                21.4              23.40  
17                22.0              23.70  
18                22.9              24.80  
19                23.8              25.20

# Transformação e seleção dos dados

## Padronização


In [397]:
norm_df = normalize_dataset(data)
norm_df

Total Rotation Speed (rpm)  Welding Speed (mm/min)  \
0                         0.00                0.000000   
1                         0.00                0.272727   
2                         0.00                0.709091   
3                         0.00                1.000000   
4                         0.30                0.000000   
5                         0.30                0.272727   
6                         0.30                0.709091   
7                         0.30                1.000000   
8                         0.50                0.000000   
9                         0.50                0.272727   
10                        0.50                0.709091   
11                        0.50                1.000000   
12                        0.75                0.000000   
13                        0.75                0.272727   
14                        0.75                0.709091   
15                        0.75                1.000000   
16                        1.00                0.000000   
17                        1.00                0.272727   
18                        1.00                0.709091   
19                        1.00                1.000000   

    Tensile Strength (MPa)  Yield Strength (MPa)  Elongation (%)  \
0                 1.000000              1.000000        0.000000   
1                 0.777778              0.846154        0.036496   
2                 0.750000              0.794872        0.081509   
3                 0.722222              0.743590        0.211679   
4                 0.722222              0.769231        0.265207   
5                 0.694444              0.717949        0.291971   
6                 0.444444              0.487179        0.301703   
7                 0.416667              0.461538        0.315085   
8                 0.638889              0.717949        0.317518   
9                 0.416667              0.487179        0.403893   
10                0.361111              0.410256        0.474453   
11                0.333333              0.333333        0.558394   
12                0.333333              0.333333        0.481752   
13                0.305556              0.256410        0.484185   
14                0.277778              0.230769        0.525547   
15                0.222222              0.153846        0.647202   
16                0.111111              0.282051        0.536496   
17                0.083333              1.000000        0.867397   
18                0.027778              0.128205        0.894161   
19                0.000000              0.000000        1.000000   

    Hardness Weld (HV)  Hardness HAZ (HV)  
0             0.852941           0.823529  
1             0.897059           0.901961  
2             0.970588           0.960784  
3             1.000000           1.000000  
4             0.794118           0.617647  
5             0.823529           0.627451  
6             0.911765           0.705882  
7             0.941176           0.823529  
8             0.735294           0.509804  
9             0.794118           0.274510  
10            0.823529           0.647059  
11            0.852941           0.745098  
12            0.382353           0.137255  
13            0.500000           0.274510  
14            0.632353           0.372549  
15            0.691176           0.490196  
16            0.000000           0.000000  
17            0.088235           0.058824  
18            0.220588           0.274510  
19            0.352941           0.352941

## Nova ordem da lista gerada automaticamente

In [398]:
import random
size = len(norm_df)
ordem = [i for i in range(size)]
ordem

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [399]:
random.shuffle(ordem)
ordem

[6, 11, 0, 3, 15, 14, 19, 17, 8, 12, 13, 1, 5, 7, 18, 9, 4, 10, 2, 16]

## Conjunto de dados de treino

In [400]:
n_treino = 15
d = norm_df.iloc[ordem[0:n_treino]]
d

Total Rotation Speed (rpm)  Welding Speed (mm/min)  \
6                         0.30                0.709091   
11                        0.50                1.000000   
0                         0.00                0.000000   
3                         0.00                1.000000   
15                        0.75                1.000000   
14                        0.75                0.709091   
19                        1.00                1.000000   
17                        1.00                0.272727   
8                         0.50                0.000000   
12                        0.75                0.000000   
13                        0.75                0.272727   
1                         0.00                0.272727   
5                         0.30                0.272727   
7                         0.30                1.000000   
18                        1.00                0.709091   

    Tensile Strength (MPa)  Yield Strength (MPa)  Elongation (%)  \
6                 0.444444              0.487179        0.301703   
11                0.333333              0.333333        0.558394   
0                 1.000000              1.000000        0.000000   
3                 0.722222              0.743590        0.211679   
15                0.222222              0.153846        0.647202   
14                0.277778              0.230769        0.525547   
19                0.000000              0.000000        1.000000   
17                0.083333              1.000000        0.867397   
8                 0.638889              0.717949        0.317518   
12                0.333333              0.333333        0.481752   
13                0.305556              0.256410        0.484185   
1                 0.777778              0.846154        0.036496   
5                 0.694444              0.717949        0.291971   
7                 0.416667              0.461538        0.315085   
18                0.027778              0.128205        0.894161   

    Hardness Weld (HV)  Hardness HAZ (HV)  
6             0.911765           0.705882  
11            0.852941           0.745098  
0             0.852941           0.823529  
3             1.000000           1.000000  
15            0.691176           0.490196  
14            0.632353           0.372549  
19            0.352941           0.352941  
17            0.088235           0.058824  
8             0.735294           0.509804  
12            0.382353           0.137255  
13            0.500000           0.274510  
1             0.897059           0.901961  
5             0.823529           0.627451  
7             0.941176           0.823529  
18            0.220588           0.274510

## Conjunto de dados de validação

In [401]:
dv = norm_df.iloc[ordem[n_treino:size]]
dv

Total Rotation Speed (rpm)  Welding Speed (mm/min)  \
9                          0.5                0.272727   
4                          0.3                0.000000   
10                         0.5                0.709091   
2                          0.0                0.709091   
16                         1.0                0.000000   

    Tensile Strength (MPa)  Yield Strength (MPa)  Elongation (%)  \
9                 0.416667              0.487179        0.403893   
4                 0.722222              0.769231        0.265207   
10                0.361111              0.410256        0.474453   
2                 0.750000              0.794872        0.081509   
16                0.111111              0.282051        0.536496   

    Hardness Weld (HV)  Hardness HAZ (HV)  
9             0.794118           0.274510  
4             0.794118           0.617647  
10            0.823529           0.647059  
2             0.970588           0.960784  
16            0.000000           0.000000

# Arquitetura da rede neural

## Representação visual


![Arquitetura da rede neural](../okuyucu_arquitecture.png "Arquitetura da rede neural")

## Número de neurônios de cada camada

In [402]:
ne = 2 # número de neurônios da camada de entrada
nh = 6 # número de neurônios da camada oculta (hidden layer)
ns = 5 # número de neurônios da camada de saída

# Treinamento passo a passo utilizando apenas a primeira linha do dataset

## Propagação


Vetor de entrada

In [403]:
input_cols = d.columns[0:2]
x = np.array(d[input_cols].iloc[0])
x

array([0.3       , 0.70909091])

Vetor de entrada com o Bias

In [404]:
bias = 1
xb = np.concatenate((x, [bias]))
xb = xb[np.newaxis]
xb = xb.T
xb

array([[0.3       ],
       [0.70909091],
       [1.        ]])

Geração dos pesos da camada escondida

In [405]:
rng = default_rng(1)

w1 = [[]]
w1[0] = np.column_stack((randn(nh, ne, -1, 1), np.ones(nh)))
w1

[array([[ 0.02364325,  0.90092739,  1.        ],
        [-0.71168077,  0.89729889,  1.        ],
        [-0.3763371 , -0.1533471 ,  1.        ],
        [ 0.65540519, -0.18160173,  1.        ],
        [ 0.09918738, -0.94488177,  1.        ],
        [ 0.50702622,  0.07628663,  1.        ]])]

vetor de entrada da camada escondida

In [406]:
v1 = np.dot(w1[0], xb)
v1

array([[1.6459324 ],
       [1.42276226],
       [0.77836184],
       [1.06784942],
       [0.35974914],
       [1.20620202]])

Vetor de saída da camada escondida

In [407]:
phi = sigmoid(v1)
phi

array([[0.83834054],
       [0.80577109],
       [0.68532694],
       [0.74418772],
       [0.58897971],
       [0.76962625]])

Vetor de saída da camada escondida com adição do bias

In [408]:
phi_b = np.concatenate((phi, [[bias]]))
print(phi_b)

[[0.83834054]
 [0.80577109]
 [0.68532694]
 [0.74418772]
 [0.58897971]
 [0.76962625]
 [1.        ]]


Geração dos pesos da camada de saída

In [409]:
rng = default_rng(2)

w2 = [[]]
w2[0] = np.column_stack((randn(ns, nh, -1, 1), np.ones(ns)))
print(w2)

[array([[-0.47677573, -0.40301771,  0.62845148, -0.81616812,  0.20020105,
         0.45712105,  1.        ],
       [-0.62419785, -0.88970675, -0.45006126,  0.31486603,  0.12453133,
        -0.69987547,  1.        ],
       [-0.13473842,  0.3385946 , -0.15443065,  0.2663688 ,  0.9348719 ,
         0.36612964,  1.        ],
       [-0.21675033, -0.62549486, -0.30807867,  0.02213195,  0.78241882,
         0.55112788,  1.        ],
       [-0.3637068 ,  0.84843379, -0.05818023,  0.38751768, -0.78558538,
        -0.79091288,  1.        ]])]


Vetor de entrada da camada de saída

In [410]:
v2 = np.dot(w2[0], phi_b)
print(v2)

[[ 0.56859872]
 [-0.77960613]
 [ 2.08466952]
 [ 1.00461074]
 [ 0.55584552]]


Vetor de saída da rede neural

In [411]:
y = sigmoid(v2)
print(y)

[[0.63843977]
 [0.31440478]
 [0.88940418]
 [0.73196414]
 [0.63549073]]


## Cálculo do erro

Valores experimentais (valores desejados)

In [412]:
output_cols = d.columns[2:]
np.array(d[output_cols].iloc[0])

array([0.44444444, 0.48717949, 0.30170316, 0.91176471, 0.70588235])

Vetor do erro (resíduo)

In [413]:
e = np.array(d[output_cols].iloc[0]) - y.T
e = e[0]
e

array([-0.19399533,  0.17277471, -0.58770102,  0.17980057,  0.07039162])

Erro quadrático

In [414]:
np.dot(e, e.T)/2

0.22508050076848196

## Retropropagação

### Cálculo dos deltas


In [415]:
delta_2 = np.dot(np.diag(e), (1 - y) * y)
delta_2

array([[-0.0447808 ],
       [ 0.03724235],
       [-0.05780885],
       [ 0.03527555],
       [ 0.01630567]])

In [440]:
v_delta_2 = np.dot(drop(w2[0].T, -1), delta_2)
v_delta_2

array([[-0.0076836 ],
       [-0.04289147],
       [-0.04779275],
       [ 0.03997599],
       [-0.04358044],
       [-0.06115582]])

In [427]:
delta_1 = np.dot(np.diag(((1 - phi) * phi).T[0]), v_delta_2)
delta_1

array([[-0.00104132],
       [-0.00671269],
       [-0.01030669],
       [ 0.00761032],
       [-0.01055007],
       [-0.01084303]])

### Atualização dos pesos


In [441]:
eta = 0.02
phi_b.T

array([[0.83834054, 0.80577109, 0.68532694, 0.74418772, 0.58897971,
        0.76962625, 1.        ]])

In [444]:
delta_w2 = eta * np.dot(delta_2, phi_b.T)
delta_w2

array([[-0.00075083, -0.00072166, -0.00061379, -0.00066651, -0.0005275 ,
        -0.00068929, -0.00089562],
       [ 0.00062444,  0.00060018,  0.00051046,  0.00055431,  0.0004387 ,
         0.00057325,  0.00074485],
       [-0.00096927, -0.00093161, -0.00079236, -0.00086041, -0.00068096,
        -0.00088982, -0.00115618],
       [ 0.00059146,  0.00056848,  0.00048351,  0.00052503,  0.00041553,
         0.00054298,  0.00070551],
       [ 0.00027339,  0.00026277,  0.00022349,  0.00024269,  0.00019207,
         0.00025099,  0.00032611]])

In [451]:
delta_w1 = eta * np.dot(delta_1, xb.T)
delta_w1

array([[-6.24794647e-06, -1.47678735e-05, -2.08264882e-05],
       [-4.02761275e-05, -9.51981195e-05, -1.34253758e-04],
       [-6.18401692e-05, -1.46167673e-04, -2.06133897e-04],
       [ 4.56619449e-05,  1.07928233e-04,  1.52206483e-04],
       [-6.33003987e-05, -1.49619124e-04, -2.11001329e-04],
       [-6.50581773e-05, -1.53773874e-04, -2.16860591e-04]])